const QUESTIONS = [
  {
    topic: "os",
    text: "Explain the main purpose of an operating system?",
    marks: "10",
    difficulty: "easy",
    id: 1,
  },
  {
    topic: "os",
    text: "What is demand paging?",
    marks: "10",
    difficulty: "easy",
    id: 2,
  },
  {
    topic: "os",
    text: "What is kernel?",
    marks: "10",
    difficulty: "easy",
    id: 3,
  },
  {
    topic: "os",
    text: "What are real-time systems?",
    marks: "10",
    difficulty: "easy",
    id: 4,
  },
  {
    topic: "os",
    text: "What is a virtual memory?",
    marks: "10",
    difficulty: "easy",
    id: 5,
  },
  {
    topic: "os",
    text: "What is time- sharing system?",
    marks: "12.5",
    difficulty: "medium",
    id: 6,
  },
  {
    topic: "os",
    text: "What is SMP?",
    marks: "12.5",
    difficulty: "medium",
    id: 7,
  },
  {
    topic: "os",
    text: "How are server systems classified?",
    marks: "12.5",
    difficulty: "medium",
    id: 8,
  },
  {
    topic: "os",
    text: "What is asymmetric clustering?",
    marks: "12.5",
    difficulty: "medium",
    id: 9,
  },
  {
    topic: "os",
    text: "What is a thread?",
    marks: "20",
    difficulty: "hard",
    id: 10,
  },
  {
    topic: "os",
    text: "What are the advantages of a multiprocessor system?",
    marks: "20",
    difficulty: "hard",
    id: 11,
  },
  {
    topic: "algo",
    text: "What is an algorithm?",
    marks: "10",
    difficulty: "easy",
    id: 12,
  },
  {
    topic: "algo",
    text: "What is time complexity of Binary Search?",
    marks: "10",
    difficulty: "easy",
    id: 13,
  },
  {
    topic: "algo",
    text: "Can Binary Search be used for linked lists?",
    marks: "10",
    difficulty: "easy",
    id: 14,
  },
  {
    topic: "algo",
    text: "How to find if two given rectangles overlap?",
    marks: "10",
    difficulty: "easy",
    id: 15,
  },
  {
    topic: "algo",
    text: "How to find angle between hour and minute hands at a given time?",
    marks: "10",
    difficulty: "easy",
    id: 16,
  },
  {
    topic: "algo",
    text: "When does the worst case of QuickSort occur?",
    marks: "12.5",
    difficulty: "medium",
    id: 17,
  },
  {
    topic: "algo",
    text: "How to count inversions in a sorted array?",
    marks: "12.5",
    difficulty: "medium",
    id: 18,
  },
  {
    topic: "algo",
    text:
      "Given a big array, how to efficiently find k’th largest element in it?",
    marks: "12.5",
    difficulty: "medium",
    id: 19,
  },
  {
    topic: "algo",
    text:
      "How to write an efficient method to calculate x raise to the power n?",
    marks: "12.5",
    difficulty: "medium",
    id: 20,
  },
  {
    topic: "algo",
    text: "Whats is an object?",
    marks: "20",
    difficulty: "hard",
    id: 21,
  },
  {
    topic: "algo",
    text: "What is an arrow function?",
    marks: "20",
    difficulty: "hard",
    id: 22,
  },
];
export default QUESTIONS;
